/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignment2;

import javax.swing.JOptionPane;

/**
 *
 * @author Aman
 */
public class PeerGUI extends javax.swing.JFrame {
// Field declaration for multicast peer
    MulticastPeer msp;

    /**
     * Creates new form PeerGUI
     */
    public PeerGUI() {
        initComponents();
    }
//bind MulticassPeer into the GUI
    public PeerGUI(MulticastPeer msp) {
        this.msp = msp;
        this.initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        receptionPortTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        groupPortTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        groupIpTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        peerIdTextField = new javax.swing.JTextField();
        setButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        queryTextField = new javax.swing.JTextField();
        queryButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        answerTextField = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Peer ID");

        receptionPortTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receptionPortTextFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Group Port");

        groupPortTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupPortTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Group IP");

        groupIpTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupIpTextFieldActionPerformed(evt);
            }
        });

        jLabel4.setText("Reception Port");

        peerIdTextField.setToolTipText("Enter either PPP1, or PPP2, or PPP3");
        peerIdTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peerIdTextFieldActionPerformed(evt);
            }
        });

        setButton.setText("SET");
        setButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Question");

        queryTextField.setEnabled(false);
        queryTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                queryTextFieldActionPerformed(evt);
            }
        });

        queryButton.setText("Query");
        queryButton.setEnabled(false);
        queryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                queryButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("Answer Board");

        answerTextField.setColumns(20);
        answerTextField.setRows(5);
        jScrollPane1.setViewportView(answerTextField);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(groupIpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(peerIdTextField))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(queryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(queryButton)
                        .addGap(0, 18, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(groupPortTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(receptionPortTextField)
                        .addGap(18, 18, 18)
                        .addComponent(setButton)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(262, 262, 262))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(groupIpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(peerIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(groupPortTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(receptionPortTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(setButton))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(queryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(queryButton))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void groupIpTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupIpTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_groupIpTextFieldActionPerformed

    private void peerIdTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peerIdTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_peerIdTextFieldActionPerformed

    private void receptionPortTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receptionPortTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_receptionPortTextFieldActionPerformed
// Method that call other services to run
    private void setButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setButtonActionPerformed
        if (peerIdTextField.getText().isEmpty() || groupIpTextField.getText().isEmpty() || groupIpTextField.getText().isEmpty() || receptionPortTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Field missing", "Error", JOptionPane.ERROR_MESSAGE);
            throw new IllegalArgumentException("Field missing");

        }

        this.msp.runServices(peerIdTextField.getText(), groupIpTextField.getText(), Integer.parseInt(groupPortTextField.getText()), Integer.parseInt(receptionPortTextField.getText()));
    }//GEN-LAST:event_setButtonActionPerformed
// method that multicast questions
    private void queryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_queryButtonActionPerformed
        this.msp.multiCastQuestions(queryTextField.getText());

    }//GEN-LAST:event_queryButtonActionPerformed

    private void groupPortTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupPortTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_groupPortTextFieldActionPerformed

    private void queryTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_queryTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_queryTextFieldActionPerformed
    // Method that displays  the text in answer text field
    public void display(String text) {
        answerTextField.append(text);
        answerTextField.append("\n");
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea answerTextField;
    private javax.swing.JTextField groupIpTextField;
    private javax.swing.JTextField groupPortTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField peerIdTextField;
    private javax.swing.JButton queryButton;
    private javax.swing.JTextField queryTextField;
    private javax.swing.JTextField receptionPortTextField;
    private javax.swing.JButton setButton;
    // End of variables declaration//GEN-END:variables

    // Mehtod that controls the fields
    void displayQuery(boolean b, boolean s) {
        JOptionPane.showMessageDialog(rootPane, "Connection Successful");
        this.queryButton.setEnabled(b);
        this.queryTextField.setEnabled(b);
        this.setButton.setEnabled(s);
        this.groupIpTextField.setEnabled(s);
        this.receptionPortTextField.setEnabled(s);
        this.groupPortTextField.setEnabled(s);
        this.peerIdTextField.setEnabled(s);
    }
}
